/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementCity: typeof import('./src/components/element-plus/ElementCity.vue')['default']
    ElementContainer: typeof import('./src/components/element-plus/ElementContainer.vue')['default']
    ElementDatetime: typeof import('./src/components/element-plus/ElementDatetime.vue')['default']
    ElementEditor: typeof import('./src/components/element-plus/ElementEditor.vue')['default']
    ElementForm: typeof import('./src/components/element-plus/ElementForm.vue')['default']
    ElementIcon: typeof import('./src/components/element-plus/ElementIcon.vue')['default']
    ElementLayout: typeof import('./src/components/element-plus/ElementLayout.vue')['default']
    ElementMenu: typeof import('./src/components/element-plus/ElementMenu.vue')['default']
    ElementNav: typeof import('./src/components/element-plus/ElementNav.vue')['default']
    ElementShrink: typeof import('./src/components/element-plus/ElementShrink.vue')['default']
    ElementTab: typeof import('./src/components/element-plus/ElementTab.vue')['default']
    ElementTable: typeof import('./src/components/element-plus/ElementTable.vue')['default']
    ElementUpload: typeof import('./src/components/element-plus/ElementUpload.vue')['default']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FullCalendar: typeof import('./src/components/fullcalendar/FullCalendar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/swiper/Swiper.vue')['default']
    SwiperSlider: typeof import('./src/components/swiper/SwiperSlider.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
